/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./app/**/*.{js,ts,jsx,tsx,mdx}", "./components/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        "on-error": "#ffffff",
        "tertiary-container": "#50586e",
        "secondary-fixed": "#ffdcc3",
        "on-background": "#191c1e",
        "on-primary-fixed": "#00210b",
        "on-tertiary-container": "#c7cee9",
        "tertiary-fixed-dim": "#bec6e0",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#fe932c",
        "surface-container": "#eceef0",
        "on-primary-fixed-variant": "#005226",
        "on-surface": "#191c1e",
        tertiary: "#394156",
        "on-tertiary-fixed-variant": "#3f465c",
        error: "#ba1a1a",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#dae2fd",
        secondary: "#904d00",
        "on-primary": "#ffffff",
        "on-primary-container": "#93e0a2",
        "primary-fixed": "#a6f4b5",
        "on-tertiary": "#ffffff",
        "outline-variant": "#bfc9bd",
        "inverse-on-surface": "#eff1f3",
        "surface-container-highest": "#e0e3e5",
        "surface-dim": "#d8dadc",
        "primary-fixed-dim": "#8bd79b",
        "secondary-fixed-dim": "#ffb77d",
        "on-surface-variant": "#404940",
        "on-error-container": "#93000a",
        surface: "#f7f9fb",
        outline: "#707a6f",
        "surface-container-low": "#f2f4f6",
        background: "#f7f9fb",
        primary: "#004c22",
        "surface-variant": "#e0e3e5",
        "surface-bright": "#f7f9fb",
        "primary-container": "#166534",
        "on-secondary-fixed": "#2f1500",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#6e3900",
        "on-tertiary-fixed": "#131b2e",
        "surface-tint": "#1f6c3a",
        "inverse-primary": "#8bd79b",
        "on-secondary-container": "#663500",
        "surface-container-high": "#e6e8ea",
        "inverse-surface": "#2d3133",
        "charcoal-slate": "#0F172A",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "stack-xs": "0.25rem",
        "stack-sm": "0.5rem",
        "stack-md": "1rem",
        "stack-lg": "2rem",
        gutter: "1.5rem",
        "margin-mobile": "1rem",
        "container-max": "1280px",
      },
      fontFamily: {
        "body-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "technical-code": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "technical-code": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};
